###
POST http://localhost:5000/users

###
GET http://localhost:5000/users

###
POST http://localhost:5000/questions

###
GET http://localhost:5000/questions

##### Employee - Clouse Table
###
POST http://localhost:5000/employees

###
GET http://localhost:5000/employees

###
GET http://localhost:5000/employees/roots

###
GET http://localhost:5000/employees/descendants

###
GET http://localhost:5000/employees/ancestors

###
GET http://localhost:5000/employees/directly-ancestor

##### TreeNested - Nested Set
###
POST http://localhost:5000/trees-nested

###
GET http://localhost:5000/trees-nested

##### Materialized Path
POST http://localhost:5000/materialized-paths

###
GET http://localhost:5000/materialized-paths

##### BaseEntity - Test BaseService
###
POST http://localhost:5000/base-test

### 
PATCH http://localhost:5000/base-test/ae5dfd61-890b-47e8-94e3-ae30ba897d7a